### ISSUE TITLE
Service redirection not working

### ISSUE THREAD

**Issue by jayanthkaturi** [Siecje/nginx-auth-proxy#1]
Hi @Siecje.  I tried to test this module, but by following the procedure on readme, I don't see the service page. 

As far as I understand, the work flow for first time is, user goes to ```/``` and ```auth_request``` directive sends this to authenticator.py's ```authenticate()``` method which returns 401 ```(abort(401))```. This is caught by ```error_page``` directive and it sends request to ```/login``` which displays ```login.html``` after executing ```login()``` method in authenticator.py . When the user fills the form with ```username = admin```, this returns ```resp``` object. This return object is sent to ```/login``` itself right? How will nginx's ```proxy_pass http://backend/``` get executed here?

**Comment by Siecje** [comment]
Yes authentication is handled by https://github.com/Siecje/nginx-auth-proxy/blob/master/authenticator.py#L51

After authentication success you will be redirected to the initial request address. In your example `/`, then there will be authentication again which should succeed.

I'm curious how did you find this?

**Comment by jayanthkaturi** [comment]
@Siecje  I am using nginx/1.6.2 and python 2.7. Can you test it out and see if it's working with this configuration? It's not working on my system. 

I was searching for authentication to services on ngnix and google search directed me to this project. :)

**Comment by Siecje** [comment]
This is very much a work in progress and is not working.

**Comment by blafasel42** [comment]
Had the same problem.
The X-Target header is not set in the existing configuration for the /login route.
You need to chnage the /login part like this:
`       
        location /login {
            proxy_pass http://authenticator/login;
            proxy_set_header X-Target $request_uri;
        }
`
similar example can be seen here:
https://github.com/nginxinc/nginx-ldap-auth/blob/master/nginx-ldap-auth.conf

**Comment by Siecje** [comment]
@blafasel42 Added in commit https://github.com/Siecje/nginx-auth-proxy/commit/78c952b517a3efc8e316123362141bd2b1d8bf0a

**Comment by Siecje** [comment]
@blafasel42 With that change I can visit the service directly. http://localhost:9000

When I try to visit http://localhost:9000 it should redirect me to the authenticator http://localhost:8000 and I should only be able to visit http://localhost:9000 after I login.

**Comment by Siecje** [comment]
@krugar100 Service redirection is now working as of https://github.com/Siecje/nginx-auth-proxy/commit/07e2fddf838e61bbf2f48a3284fe2c55fa632668

**Comment by jayanthkaturi** [comment]
@Siecje I also made another fix [here](https://github.com/krugar100/nginx-auth-proxy/commit/53f671ee1e9b9a951d3d01e0d3c2a962e9c9065a).

**Comment by Siecje** [comment]
@krugar100 Awesome!

I'm closing this because it is now working and you got it working as well.
