### ISSUE TITLE
Good readme or instructions?

### ISSUE THREAD

**Issue by krishnakanthpps** [Siecje/nginx-auth-proxy#2]
Hi..

I have problem exactly what is put in the Diagram. I am trying to authenticate 2 apps over same nginx. 

I think your solution solves my problem, but I am unable to find understand some pieces of it. 

Is there a good read me or instruction on how to get thing up and working?

**Comment by Siecje** [comment]
Have you been able to get the `authenticator` and `service` in the repo working?

The instructions are at the bottom of the README.

What step is confusing or not working and what is the error message?

**Comment by krishnakanthpps** [comment]
Here is my issue. 

I have a php app and a golang based angular js app and both have a nginx webserver front end. And this is setup on ubuntu 16.04. I am trying to use nginx as a reverse proxy as well. 

I want to have a SSO for them, so that if a user registers using Php app, he should be able to do a SSO to the angularjs app. 

I did the nginx full install, then set up the python pip. 

I think the next step would be I believe running the authenticator and the service, but when I run them I get the following message.. 

```
KK@VirtualBox:~$ sudo python authenticator.py &
[1] 32330
KK@VirtualBox:~$ python: can't open file 'authenticator.py': [Errno 2] No such file or directory

[1]+  Exit 2                  sudo python authenticator.py
```
So, my question is about the following lines.. 

> Configure the new service to authenticate via REMOTE_USER or add the required headers for the service to authenticator.py and nginx.conf.
> 
> Restart nginx to reload the nginx configuration.

How should I get to do this.. 

Unfortunately I am not a great expert in nginx, so wanted to see an example before I proceed. 

Let me know if you need more info. 

Thank you.

**Comment by Siecje** [comment]
You need to clone the repo and then run `authenticator.py` from the repo directory.

`pip install -r requirements.txt` also needs to be run in the repo directory (to use the requirements.txt file)

I will update the README to start with cloning the repo.

**Comment by krishnakanthpps** [comment]
I have an application running on port 80 and port 3000. Should I update them in the nginx.conf file? 

Also, php app hosts my main authentication. so how do i make it take that authentication? 

I hope you understood my dilemma.

**Comment by Siecje** [comment]
Have you been able to get the setup in the repo working? I would start with that then replace the authenticator port with the port of the PHP application.

And then once the PHP authentication is working with the Python service in the repo then replace the service port.

**Comment by krishnakanthpps** [comment]
localhost:8000 says unauthorized.. The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.

and

localhost:9000 says this is a service. 

tried restarting the nginx service and now unable to restart as it says too many symbolic links found. 

```
May 01 23:03:15 krishna-VirtualBox nginx[1211]: nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (40: Too many levels of symbolic links)
May 01 23:03:15 krishna-VirtualBox nginx[1211]: nginx: configuration file /etc/nginx/nginx.conf test failed
May 01 23:03:15 krishna-VirtualBox systemd[1]: nginx.service: Control process exited, code=exited status=1
May 01 23:03:15 krishna-VirtualBox systemd[1]: Failed to start A high performance web server and a reverse proxy server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nginx.service has failed.
-- 
-- The result is failed.
```
Working on fixing this..

**Comment by krishnakanthpps** [comment]
services are up.. but like as I said.. localhost:8081 is unreachable, localhost:8000 is unauthorized and localhost:9000 says this is a service.. 

followed all the steps as mentioned.

**Comment by Siecje** [comment]
Have you restarted nginx after changing the config?

`sudo service nginx restart`

**Comment by krishnakanthpps** [comment]
Yes. Restart fails due to high number of symbolic links.  

I think I need to find how to get rid of that error then things might get solved. 

Any suggestions on how to get rid of the symbolics error message when running inside the venv? 

What I did is delete the symbolic link and then start nginx from /etc/nginx, it started all fine. 

But when I do the sudo mv and the sudo ln and then do a nginx reload or restart that's when the error comes. 

Both authenticator and service are running fine. 

Also nothing else running on 8081.

**Comment by Siecje** [comment]
Hmm I have `nginx.conf` as a symbolic link.

```shell
$ cd /etc/nginx
$ ls -la 
lrwxrwxrwx   1 root root    48 Sep 19  2016 nginx.conf -> /home/siecje/Desktop/nginx-auth-proxy/nginx.conf
```

Maybe make sure it is owned by `root:root`?

Instead of a symbolic link. Can you just have `nginx.conf` as a file?

```shell
$ cd /etc/nginx
$ sudo rm nginx.conf
$ sudo touch nginx.conf
# open in an editor with sudo (so you can write to it)
$ sudo vim nginx.conf
```
And then paste in the contents of nginx.conf from the repo.

**Comment by krishnakanthpps** [comment]
Awesome. Now got it to work. Sorry for all this trouble. 

Now my next step.. I have an php app on port 80.. and another app on 3000. 
Lets say abc.com is on port 80 and xyz.abc.com or even abc.com/xyz is on 3000. 

both have their own DB where users are stored. 

Is it possible that I place this nginx auth proxy in such a way that nginx does the authentication and then user can go from abc.com to xyz.abc.com or abc.com/xyz without any need for logging in again?

Thank you in advance.

**Comment by Siecje** [comment]
You will need an app that can authenticate all users.

You will need to configure the apps that you want to use to accept and trust an HTTP header with the username.

https://github.com/Siecje/nginx-auth-proxy/blob/7c9f371a0318371a480ec73bb504558365f9ced5/supported.md

**Comment by krishnakanthpps** [comment]
Let me try it. My second app is Grafana and I want to integrate it with Laravel.

Let me try and reach out to you.

________________________________

**Comment by krishnakanthpps** [comment]
A few questions. 

I have my app hosted on port 80 on localhost and its login at /login and users are saved in MySQL DB
I have my grafana hosted on port 3000 on localhost

I have my default conf at /etc/nginx/sites-available/ 

What steps do I need to take so that if a user is logged in at localhost/login and then if a user goes to localhost/grafana, he should not be prompted for a login screen again. 

Should I change the /etc/nginx/nginx.conf so that it kind of mirrors default conf ? 

or are there any other changes.

**Comment by Siecje** [comment]
Since the nginx config in the repo uses `http {` it needs to be the top level config (`/etc/nginx/nginx.conf`).

You need to use the config in the repo and save it to `/etc/nginx/nginx.conf`. Change the authenticator port to 80.
https://github.com/Siecje/nginx-auth-proxy/blob/7c9f371a0318371a480ec73bb504558365f9ced5/nginx.conf#L13

Set the service port to 3000.
https://github.com/Siecje/nginx-auth-proxy/blob/7c9f371a0318371a480ec73bb504558365f9ced5/nginx.conf#L9

Users will still access the service through 8081 as specified here.
https://github.com/Siecje/nginx-auth-proxy/blob/7c9f371a0318371a480ec73bb504558365f9ced5/nginx.conf#L19

You also need to make sure that the authenticator application is setting the correct headers that you need. For Grafana it is `X-WEBAUTH-USER` see the authenticator in the repo.
https://github.com/Siecje/nginx-auth-proxy/blob/7c9f371a0318371a480ec73bb504558365f9ced5/authenticator.py#L65

You need to configure Grafana to use and trust the header for authentication
http://docs.grafana.org/installation/configuration/#auth-proxy

**Comment by krishnakanthpps** [comment]
Changed the authenticator port to 80.
Changed the service port to 3000
tried accessing from 8081.  Got 500 Internal Server Error. 

```
2017/05/04 20:25:41 [error] 6461#6461: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", subrequest: "/auth-proxy", upstream: "http://127.0.0.1:80/", host: "localhost:8081", referrer: "http://localhost:8081/login"
2017/05/04 20:25:41 [debug] 6461#6461: *6 http next upstream, 2
2017/05/04 20:25:41 [debug] 6461#6461: *6 free rr peer 1 4
2017/05/04 20:25:41 [debug] 6461#6461: *6 finalize http upstream request: 502
2017/05/04 20:25:41 [debug] 6461#6461: *6 finalize http proxy request
2017/05/04 20:25:41 [debug] 6461#6461: *6 close http upstream connection: 4
2017/05/04 20:25:41 [debug] 6461#6461: *6 free: 00005584C0FD5270, unused: 48
2017/05/04 20:25:41 [debug] 6461#6461: *6 event timer del: 4: 1493909801258
2017/05/04 20:25:41 [debug] 6461#6461: *6 reusable connection: 0
2017/05/04 20:25:41 [debug] 6461#6461: *6 http finalize request: 502, "/auth-proxy?" a:1, c:2
2017/05/04 20:25:41 [debug] 6461#6461: *6 auth request done s:0
2017/05/04 20:25:41 [debug] 6461#6461: *6 http special response: 502, "/auth-proxy?"
2017/05/04 20:25:41 [debug] 6461#6461: *6 xslt filter header
2017/05/04 20:25:41 [debug] 6461#6461: *6 http finalize request: 0, "/auth-proxy?" a:1, c:2
2017/05/04 20:25:41 [debug] 6461#6461: *6 auth request done s:502
2017/05/04 20:25:41 [debug] 6461#6461: *6 http wake parent request: "/?"
2017/05/04 20:25:41 [debug] 6461#6461: *6 http posted request: "/?"
2017/05/04 20:25:41 [debug] 6461#6461: *6 access phase: 11
2017/05/04 20:25:41 [debug] 6461#6461: *6 auth request handler
2017/05/04 20:25:41 [debug] 6461#6461: *6 auth request set variables
2017/05/04 20:25:41 [error] 6461#6461: *6 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8081", referrer: "http://localhost:8081/login"
2017/05/04 20:25:41 [debug] 6461#6461: *6 http finalize request: 500, "/?" a:1, c:1
2017/05/04 20:25:41 [debug] 6461#6461: *6 http special response: 500, "/?"
2017/05/04 20:25:41 [debug] 6461#6461: *6 http set discard body
2017/05/04 20:25:41 [debug] 6461#6461: *6 xslt filter header
2017/05/04 20:25:41 [debug] 6461#6461: *6 HTTP/1.1 500 Internal Server Error
Server: nginx/1.10.0 (Ubuntu)
Date: Thu, 04 May 2017 14:55:41 GMT
Content-Type: text/html
Content-Length: 604
Connection: close
```
realized that it is not going to my php app at all, changed the server conf part, where I inserted the following so that it recognizes where is my laravel app. 

```
root /var/www/aptim/public;
	server_name aptim;
```
It still gives 500 error. 

From this line I think it is getting redirected from localhost:8081 to localhost:80/auth_proxy which doesnt exist and thus giving an error of 500.  I am guessing this from the fiddler part. 

When I try to access localhost:8081/login, I get a 502 error. 

I think I am missing some basic fundamental tweaks which are causing these issues. 

Any more suggestions?

**Comment by Siecje** [comment]
To use the same nginx config to server your PHP authenticator app you need another `server {}` section in the config with 

```
server {
    listen 80;
    root /var/www/aptim/public;
    server_name aptim;
}
```

Or whatever else is required to serve the PHP app with nginx. 

You might want to start with an nginx config that just serves the PHP authenticator application.

**Comment by Siecje** [comment]
Have you had any luck getting it working?

**Comment by krishnakanthpps** [comment]
Hey...

I couldn't get it to work that day. Need to find some more time to debug further.

Will update you in couple of days.
________________________________

**Comment by Siecje** [comment]
I have updated the code and instructions.

**Comment by Siecje** [comment]
I'm going to close this. Let me know if you are still having issues.
